# Generated by Django 4.2.6 on 2023-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_post_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdfundingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('media_file', models.FileField(upload_to='campaigns/')),
                ('communities', models.ManyToManyField(blank=True, to='myapp.community')),
            ],
        ),
    ]
