# Generated by Django 4.2.6 on 2023-10-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='total_donors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
