# Generated by Django 4.2.6 on 2023-10-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0013_crowdfundingcampaign_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcontent',
            name='saved_posts',
        ),
        migrations.AddField(
            model_name='savedcontent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='savedcontent',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
