# Generated by Django 4.2.6 on 2023-10-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_campaignlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlike',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AlterUniqueTogether(
            name='campaignlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
