# Generated by Django 4.2.6 on 2023-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_resourcecomment_likes_count_resourcelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecomment',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='resource',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
