# Generated by Django 4.2.6 on 2023-11-01 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0022_campaigncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
