# Generated by Django 4.2.6 on 2023-11-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_crowdfundingcampaign_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
