# Generated by Django 4.2.6 on 2023-11-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_crowdfundingcampaign_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdfundingcampaign',
            old_name='created_at',
            new_name='published_at',
        ),
    ]
