# Generated by Django 4.2.6 on 2023-11-05 04:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0025_rename_created_at_crowdfundingcampaign_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingcampaign',
            name='likers',
        ),
        migrations.AlterUniqueTogether(
            name='campaignlike',
            unique_together={('user', 'campaign')},
        ),
    ]
