# Generated by Django 4.2.6 on 2023-11-05 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0026_remove_crowdfundingcampaign_likers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingcampaign',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
