# Generated by Django 4.2.6 on 2023-11-07 23:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0027_crowdfundingcampaign_likers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
