# Generated by Django 4.2.6 on 2023-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='wants_to_apply',
            field=models.BooleanField(default=False),
        ),
    ]
