# Generated by Django 4.2.6 on 2023-12-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_application_wants_to_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='trial',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.trial'),
            preserve_default=False,
        ),
    ]
