# Generated by Django 4.2.6 on 2024-01-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_chatgroup_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='chat_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='myapp.chatgroup'),
        ),
    ]
