# Generated by Django 4.2.6 on 2024-01-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_messagenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_type',
        ),
    ]
