# Generated by Django 4.2.6 on 2024-01-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
