# Generated by Django 4.2.6 on 2024-01-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
