# Generated by Django 4.2.6 on 2024-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_link',
            field=models.URLField(blank=True),
        ),
    ]
