# Generated by Django 4.2.6 on 2024-01-30 11:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_userprofile_personal_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='participation_criteria',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
